name: Docker CD Latest

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:

  releases-deploy:

    name: Docker Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and Publish Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build . -t zekro/shinpuru:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push zekro/shinpuru:latest
