name: Docker CD

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Populate info embeds
        run: bash ./scripts/populateinfo.sh

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - if: startsWith(github.ref, 'refs/heads/master')
        run: echo "TAG=latest" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/heads/dev')
        run: echo "TAG=canary" >> $GITHUB_ENV
        
      - if: startsWith(github.ref, 'refs/tags')
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            zekro/shinpuru:${{ env.TAG }}
            ghcr.io/zekrotja/shinpuru:${{ env.TAG }}